// -----------------------------------------------------------------------------
// CuteJet by CyaNn & ALGEA

include("../includes/CuteJet.include.base");

include("../includes/CuteJet.include.level");
include("../includes/CuteJet.include.hero");
include("../includes/CuteJet.include.gems");
include("../includes/CuteJet.include.enemies");
include("../includes/CuteJet.include.shoot");

include("../includes/CuteJet.include.end");

set music = game.createSound("Loop/Vibraphone")
music.playLoop();
